spring:
  application:
    name: Dable
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DATASOURCE_PASSWORD}
    username: ${DATASOURCE_USERNAME}
    url: ${DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      url: ${REDIS_URL}

auth:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

captcha:
  secret: ${CAPTCHA_SECRET}
  verify_url: ${CAPTCHA_VERIFY_URL}

yandex:
  s3:
    access-key: ${YANDEX_S3_ACCESS_KEY}
    secret-key: ${YANDEX_S3_SECRET_KEY}
    bucket: ${YANDEX_S3_BUCKET}
    region: ${YANDEX_S3_REGION}
    endpoint: ${YANDEX_S3_ENDPOINT}

app:
  registration:
    confirmation-url-template: ${CONFIRMATION_URL_TEMPLATE}
    redis-confirmation-token-expiration-minutes: ${REDIS_CONFIRMATION_TOKEN_EXPIRATION_MINUTES}