spring:
  application:
    name: demo
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DATASOURCE_PASSWORD}
    username: ${DATASOURCE_USERNAME}
    url: ${DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.example.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true