name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Build JAR (skip tests)
        run: ./gradlew clean build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: $({ secrets.DOCKER_USERNAME })
          password: $({ secrets.DOCKER_PASSWORD })
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: vovgoo/dable:latest
